import { apiGet, apiPatch } from './api';

export const alertService = {
  getAlerts: async (filters = {}) => {
      const params = {};
      if (filters.status && filters.status !== 'ALL') params.status = filters.status;
      params.limit = 200;

      const response = await apiGet('/alerts', params);
      const data = response.data || response;
      let alerts = data.alerts || (Array.isArray(data) ? data : []);

      alerts = alerts.map((a) => ({
        id: a.id,
        alert_type: a.alert_type,
        entity_id: a.entity_id,
        case_id: a.case_id,
        risk_level: a.risk_level || 'LOW',
        risk_score: a.risk_score || 0,
        reason: a.reason || '',
        confidence: a.confidence || 0,
        status: a.status || 'NEW',
        assigned_to: a.assigned_to,
        created_at: a.created_at,
        title: a.alert_type || 'Alert',
        summary: a.reason || 'Alert generated by analytical system.',
        target_entity: a.entity_id || 'Unknown',
        severity: a.risk_level || 'LOW',
        timestamp: a.created_at ? new Date(a.created_at).toLocaleString() : 'N/A',
        why_flagged: [a.reason || 'Analytical detection triggered.'],
        recommended_action: 'Requires human verification and investigation review.',
        _raw: a
      }));

      if (filters.severity && filters.severity !== 'ALL') {
        alerts = alerts.filter((a) => a.severity === filters.severity);
      }
      if (filters.type && filters.type !== 'ALL') {
        alerts = alerts.filter((a) => a.alert_type === filters.type);
      }

      return alerts;
  },

  getAlert: async (alertId) => {
    try {
      const response = await apiGet(`/alerts/${alertId}`);
      const a = response.data || response;
      return {
        id: a.id,
        alert_type: a.alert_type,
        entity_id: a.entity_id,
        case_id: a.case_id,
        risk_level: a.risk_level || 'LOW',
        risk_score: a.risk_score || 0,
        reason: a.reason || '',
        confidence: a.confidence || 0,
        status: a.status || 'NEW',
        created_at: a.created_at,
        title: a.alert_type || 'Alert',
        summary: a.reason || 'Alert generated by analytical system.',
        target_entity: a.entity_id || 'Unknown',
        severity: a.risk_level || 'LOW',
        timestamp: a.created_at ? new Date(a.created_at).toLocaleString() : 'N/A',
        why_flagged: [a.reason || 'Analytical detection triggered.'],
        recommended_action: 'Requires human verification and investigation review.',
        _raw: a
      };
    } catch (error) {
      console.error('Failed to fetch alert:', error);
      throw error;
    }
  },

  updateStatus: async (alertId, status) => {
    const response = await apiPatch(`/alerts/${alertId}/status?status=${encodeURIComponent(status)}`);
    return { success: true, alert: response.data || response };
  }
};

export default alertService;
