export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  SENIOR_INVESTIGATOR: 'SENIOR_INVESTIGATOR',
  INVESTIGATOR: 'INVESTIGATOR',
  ANALYST: 'ANALYST',
  STATE_OFFICER: 'STATE_OFFICER',
  VIEWER: 'VIEWER'
};

export const PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_CASES: 'VIEW_CASES',
  CREATE_CASE: 'CREATE_CASE',
  UPLOAD_DATA: 'UPLOAD_DATA',
  VIEW_ENTITIES: 'VIEW_ENTITIES',
  VIEW_NETWORK: 'VIEW_NETWORK',
  VIEW_ALERTS: 'VIEW_ALERTS',
  VIEW_EVIDENCE: 'VIEW_EVIDENCE',
  GENERATE_REPORT: 'GENERATE_REPORT',
  REQUEST_CROSS_STATE_ACCESS: 'REQUEST_CROSS_STATE_ACCESS',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  REVOKE_ACCESS: 'REVOKE_ACCESS'
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [ROLES.ADMIN]: ALL_PERMISSIONS,
  [ROLES.SENIOR_INVESTIGATOR]: ALL_PERMISSIONS.filter(p => p !== PERMISSIONS.MANAGE_ROLES),
  [ROLES.INVESTIGATOR]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CASES,
    PERMISSIONS.CREATE_CASE,
    PERMISSIONS.UPLOAD_DATA,
    PERMISSIONS.VIEW_ENTITIES,
    PERMISSIONS.VIEW_NETWORK,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.VIEW_EVIDENCE,
    PERMISSIONS.GENERATE_REPORT,
    PERMISSIONS.REQUEST_CROSS_STATE_ACCESS
  ],
  [ROLES.ANALYST]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CASES,
    PERMISSIONS.VIEW_ENTITIES,
    PERMISSIONS.VIEW_NETWORK,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.VIEW_EVIDENCE,
    PERMISSIONS.GENERATE_REPORT
  ],
  [ROLES.STATE_OFFICER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CASES,
    PERMISSIONS.VIEW_ENTITIES,
    PERMISSIONS.VIEW_NETWORK,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.REQUEST_CROSS_STATE_ACCESS
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_CASES,
    PERMISSIONS.VIEW_ENTITIES,
    PERMISSIONS.VIEW_NETWORK
  ]
};

export const hasPermission = (userRole, permission) => {
  if (!userRole) return false;
  const permissions = ROLE_PERMISSIONS[userRole] || [];
  return permissions.includes(permission);
};
